### ISSUE TITLE
Last changes crashes yad

### ISSUE THREAD

**Issue by Thanatermesis** [step-/yad#3]
When trying to run it, It simply crashes with many (not all) options, actually it crashes on a Live system but not in my main computer, which is strange

This is the GDB result from a segfault running simply "yad":

```
#0  0x00007ffff7418d76 in  () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff75e6d68 in g_strconcat () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x000055555557dc9f in set_comment (s=<optimized out>, key=0x5555555863f0 "width", kf=0x5555555e3850) at util.c:108
        comment = <optimized out>
        kf = 0x5555555e3850
        context = <optimized out>
#3  write_settings () at util.c:122
        kf = 0x5555555e3850
        context = <optimized out>
#4  0x000055555557e355 in read_settings () at util.c:99
        kf = <optimized out>
        filename = 0x55555561c800 "/home/eliveuser/.config/yad.conf"
#5  0x0000555555569c9e in main (argc=<optimized out>, argv=<optimized out>) at main.c:776
        ctx = <optimized out>
        err = 0x0
        w = 0x7fff
        h = 0xffffe1b8
        str = <optimized out>


registers:
rax            0x1                 0x1
rbx            0x7fffffffdf90      0x7fffffffdf90
rcx            0x1                 0x1
rdx            0x7fffffffdfa0      0x7fffffffdfa0
rsi            0x5555555863e1      0x5555555863e1
rdi            0x1                 0x1
rbp            0x555555582e2f      0x555555582e2f
rsp            0x7fffffffdf68      0x7fffffffdf68
r8             0x800               0x800
r9             0x0                 0x0
r10            0x555555558ee2      0x555555558ee2
r11            0x7ffff75e6ce0      0x7ffff75e6ce0
r12            0x16                0x16
r13            0x0                 0x0
r14            0x7fffffffe040      0x7fffffffe040
r15            0x7fffffffe078      0x7fffffffe078
rip            0x7ffff7418d76      0x7ffff7418d76
eflags         0x10293             [ CF AF SF IF RF ]
cs             0x33                0x33
ss             0x2b                0x2b
ds             0x0                 0x0
es             0x0                 0x0
fs             0x0                 0x0
gs             0x0                 0x0


current instructions:
=> 0x7ffff7418d76:      movdqu xmm4,XMMWORD PTR [rax]
   0x7ffff7418d7a:      pcmpeqb xmm4,xmm0
   0x7ffff7418d7e:      pmovmskb edx,xmm4
   0x7ffff7418d82:      test   edx,edx
   0x7ffff7418d84:      je     0x7ffff7418d8a
   0x7ffff7418d86:      bsf    eax,edx
   0x7ffff7418d89:      ret
   0x7ffff7418d8a:      and    rax,0xfffffffffffffff0
   0x7ffff7418d8e:      pcmpeqb xmm1,XMMWORD PTR [rax+0x10]
   0x7ffff7418d93:      pcmpeqb xmm2,XMMWORD PTR [rax+0x20]
   0x7ffff7418d98:      pcmpeqb xmm3,XMMWORD PTR [rax+0x30]
   0x7ffff7418d9d:      pmovmskb edx,xmm1
   0x7ffff7418da1:      pmovmskb r8d,xmm2
   0x7ffff7418da6:      pmovmskb ecx,xmm3
   0x7ffff7418daa:      shl    rdx,0x10
   0x7ffff7418dae:      shl    rcx,0x10


threads backtrace:

Thread 1 (Thread 0x7ffff63ffa00 (LWP 23374) "yad"):
#0  0x00007ffff7418d76 in  () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff75e6d68 in g_strconcat () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x000055555557dc9f in set_comment (s=<optimized out>, key=0x5555555863f0 "width", kf=0x5555555e3850) at util.c:108
#3  write_settings () at util.c:122
#4  0x000055555557e355 in read_settings () at util.c:99
#5  0x0000555555569c9e in main (argc=<optimized out>, argv=<optimized out>) at main.c:776
```

**Comment by step-** [comment]
Hi, thanks for your report.  Can you please attach your configuration file, which is listed in gdb's backtrace:

```
#4  0x000055555557e355 in read_settings () at util.c:99
        kf = <optimized out>
        filename = 0x55555561c800 "/home/eliveuser/.config/yad.conf"
```

**Comment by Thanatermesis** [comment]
I saw that too but there's no such configuration file 

On the other hand, if i create it (empty), like "touch .config/yad.conf" I can run yad without segfaulting 🤔

**Comment by step-** [comment]
Thank you! I couldn't reproduce it but I found a coding error.

**Comment by Thanatermesis** [comment]
_confirmed here that the issue is solved after updating with the last commit_
